---
title: "Week 2"
author: "David Kane"
output: html_document
---

Go to https://registrar.fas.harvard.edu/faculty-staff/courses/enrollment and scroll down to "Access the Current Course Enrollment Numbers." Click on that to download the Excel file. Create a folder in your project called `raw_data`. Move the Excel file into that folder. 

Load **tidyverse**, **readxl** and **janitor** into your setup chunk. You may need to install the packages **readxl** and **janitor** if you haven't already.

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(janitor)
knitr::opts_chunk$set(echo = TRUE)
```

### Scene 1

**Prompt:** Use **readxl** to read in the data and store it in an object called `raw_data`. Clean the data by cleaning any column names, skipping or cutting rows, and storing the cleaned data in an object called `en_fall_2020`. Additionally, since we will be looking only at undergraduate enrollment, get rid of any irrelevant columns, and filter to keep only courses with at least ten undergraduate students. This will get rid of any weird research courses. Look closely at your data! There is a lot of garbage to find and deal with.

Once you have finished cleaning your data, figure out the course with the highest enrollment. And figure out how many students are enrolled in Gov 50. If you get a number much lower than 151, you have done something wrong . . .



### Scene 2

**Prompt:** Create a bar plot of the 10 biggest courses. Order the plot so that courses appear in descending order. You will want to use coord_flip() to make your plot easy to read.




### Scene 3

**Prompt:** Make a bar plot of total enrollment by department for the ten smallest departments. Arrange the bar plot in ascending order.



### Scene 4

**Prompt:** Create a scatterplot of the length of course name versus enrollment for the Computer Science and Economics Department. Use `nchar()` to find the length, and include spaces. Add a linear line of best fit on your plot and scale axes appropriately.


